steps:
  # 1. 安裝依賴
  - name: 'node:20'       # 使用官方 Node.js 20 Docker 映像
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  # 2. 編譯 TypeScript
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build

  # 3. 啟動 Node.js（通常 Cloud Run 用 build artifact，不會直接啟動）
  #    如果你要打包成 Docker image，這步可以省略
  # - name: 'node:20'
  #   entrypoint: 'node'
  #   args: ['dist/index.js']

# 設定 artifacts（可選）
# artifacts:
#   objects:
#     location: 'gs://YOUR_BUCKET_NAME/dist/'
#     paths: ['dist/**']

# 設定 timeout（可選）
timeout: '1200s'  # 最長 20 分鐘
